###############################################################################
#                         docker-compose up --build -d                        #
###############################################################################

services:
  webserver:
    container_name: document-server
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - './public:/application/public'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php-fpm3
    ports:
      - '59000:80'
    restart: unless-stopped

  php-fpm3:
    container_name: php-fpm3
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    volumes:
      - .:/application
    command: php-fpm -F
    restart: unless-stopped

volumes:
  postgres_data:
